name: Simple CI/CD Simulation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - run: echo "Frontend: Installing dependencies..."
      - run: echo "Frontend: test done"
      - run: echo "Frontend: Building..."

  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - run: echo "Backend: Installing Java and Maven..."
      - run: echo "Backend: test done"
      - run: echo "Backend: Building JAR..."

  deploy:
    name: Deploy
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy: deploy done"
      - run: echo "Deploy: Frontend and backend deployed successfully!"
