name: CI for Spring and Next.js

on:
  push:
    branches:
      - main  # Ou la branche de votre choix
  pull_request:
    branches:
      - main  # Ou la branche de votre choix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2: Configuration de Java pour le projet Spring
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Étape 3: Build du projet Spring (avec Maven)
      - name: Build Spring app with Maven
        run: |
          cd backend
          mvn clean install

      # Étape 4: Configuration de Node.js pour Next.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Utilisez la version de Node.js que vous préférez

      # Étape 5: Installer les dépendances du projet Next.js
      - name: Install dependencies for Next.js
        run: |
          cd frontend
          npm install


     
